//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Satislar = new HashSet<Satislar>();
        }

        public int UrunID { get; set; }
        [Required(ErrorMessage = "Urun adini bos gecemezsiniz!")] public string UrunAd { get; set; }
        [Required(ErrorMessage = "Urun markasini bos gecemezsiniz!")] public string Marka { get; set; }
         public Nullable<short> UrunKategori { get; set; }
        [Required(ErrorMessage = "Urun fiyatini bos gecemezsiniz!")] public Nullable<decimal> Fiyat { get; set; }
        [Required(ErrorMessage = "Urun stok bilgisini bos gecemezsiniz!")] public Nullable<byte> Stok { get; set; }

        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
